### ISSUE TITLE
Add automatic code review

### ISSUE THREAD

**Issue by totorigolo** [INSAlgo/codingbattle-2018#15]
Since all (?) code review tools are :free: for open source projects :tada:, we should definitely use one in this repository! What do you think?

Take a look at:
https://github.com/marketplace/category/code-quality

**Comment by Nyrio** [comment]
Do you mean *code review* or *code quality*? Also, can you name one specific tool that we might want to use in this repo? The repo isn't a software but a bunch of solutions for the problems of the Coding Battle, and is very likely to stop receiving new solutions in a few days.

**Comment by totorigolo** [comment]
_code quality_, as in the link I put. (Codacy)[https://github.com/marketplace/codacy] maybe? It can ensure that code follows strict code style, that's what would be interesting here.

I thought it could be a nice project to try to set up such a tool, and that it could be useful for future projects as well. But yeah, maybe it's not the best one as it has quite a lot of public visibility.

You can just close this issue then.

**Comment by Nyrio** [comment]
Right, maybe I'll try out this tool on a personal project before using it on that kind of repo.
